const ROUTES = {
    SPEC: '/',
    HOME: '/HOME',
    LOGIN: '/LOGIN',
SIGNUP: '/SIGNUP',
NEWCARD: '/NEWCARD',
EDITCARD: '/EDITCARD',
FAVCARDS: '/FAVCARDS',
ABOUT: '/ABOUT',
}

export default ROUTES;